### PR TITLE
Added watchify to speed up rebundles

### PR DESCRIPTION
**Pull request by ispal**
I added watchify to watch changes and rebundle only the required parts. This will speed up rebundles a lot. If production flag is set, it will not use watchify.

### CODE REVIEW

**Comment by ispal** [comment]
Maybe add an boolean option to enable/disable watchify in your gulp file when you call browserify? IMO watchify is important when working with browserify as it makes build much faster after the initial build.

**Comment by skrajewski** [comment]
High level API (in this case laravel-elixir) provides additional constraints. @Daveawb has right, it breaks  an elixir flow. Boolean is simply workaround but I belive that there are better solutions.

**Comment by ispal** [comment]
I modified the code so that it should work by running gulp & gulp watch. I'm using *gulp.tasks.watch.done* to choose whether to use broserify or watchify. I still think it might be a little hackish but it works. I also added `bundler` variable to cache the bundler so it's not initiated every time task is called. Any thoughts?

**Comment by skrajewski** [comment]
Watchify has been added in #18

**Pull request closed without merging**
